### ISSUE TITLE
Update metadata and readme

### ISSUE THREAD

**Issue by rogerbinns** [utelle/apsw-sqlite3mc#1]
[project_urls](https://github.com/utelle/apsw-sqlite3mc/blob/master/setup.py#L66) contains metadata that shows up on the [pypi page](https://pypi.org/project/apsw/) in the project links section.  You can delete most of them.

Around line 845 of setup.py there is also another "url" key that should be changed - it is the Homepage link.

The author name and email show up further down the pypi page and should also be changed.

Whatever keyword is used for encryption should also be added.

The top level README.rst file needs to be completely changed.

**Comment by utelle** [comment]
> [project_urls](https://github.com/utelle/apsw-sqlite3mc/blob/master/setup.py#L66) contains metadata that shows up on the [pypi page](https://pypi.org/project/apsw/) in the project links section. You can delete most of them.

Are the tags (like _"Documentation"_) fixed keywords? Or are they taken as is as the link description? If the latter, links to the documentation of _APSW_ (your documentation) **and** to the documentation of _SQLite3 Multiple Ciphers_ could be added.

> Around line 845 of setup.py there is also another "url" key that should be changed - it is the Homepage link.

Ok, this can be set to my forked repository.

> The author name and email show up further down the pypi page and should also be changed.

Well, APSW is (and stays) your baby. I'm just bundling it with my SQLite3 variant. I'm a bit reluctant to add myself as the author here. Is it possible to have 2 author entries?

> Whatever keyword is used for encryption should also be added.

I would add simply the keyword _encryption_. And as an additional topic _Topic :: Security :: Cryptography_ could be added.

> The top level README.rst file needs to be completely changed.

Of course, the readme has to be adjusted.

**Comment by rogerbinns** [comment]
I don't remember how I got the list.  I think I found it in another project.

It is fine you being the author.  I'll adjust the readme first.

**Comment by rogerbinns** [comment]
I've made changes for your review.

The project here at github also needs metadata changes - the About and link in the top right of https://github.com/utelle/apsw-sqlite3mc

**Comment by rogerbinns** [comment]
The default branch shown at github should also be changed to sqlite3mc so it picks up the updated readme

**Comment by utelle** [comment]
> The default branch shown at github should also be changed to sqlite3mc so it picks up the updated readme

Done. `sqlite3mc` is now the default branch.
