### ISSUE TITLE
Get test pypi build working

### ISSUE THREAD

**Issue by rogerbinns** [utelle/apsw-sqlite3mc#2]
You need to create an account at https://test.pypi.org/ which will require two factor authentication.

Then in Your Account settings go to the Publishing section and add a new publisher pointing to this repository with a workflow name of build-testpypi.yml

You will also need to enable the [workflow](https://github.com/utelle/apsw-sqlite3mc/blob/master/.github/workflows/build-testpypi.yml) since that does not happen for forked repositories automatically.

**Comment by utelle** [comment]
> You need to create an account at https://test.pypi.org/ which will require two factor authentication.

Done.

> Then in Your Account settings go to the Publishing section and add a new publisher pointing to this repository with a workflow name of build-testpypi.yml

Done. Project shown in the list of pending publishers in my TestPyPI account.

For new publishers an environment name can be optionally configured. I haven't done this. If configuring an environment name is preferrable, I'll have to repeat this step.

> You will also need to enable the [workflow](https://github.com/utelle/apsw-sqlite3mc/blob/master/.github/workflows/build-testpypi.yml) since that does not happen for forked repositories automatically.

Done.

**Comment by rogerbinns** [comment]
You should create another account at regular https://pypi.org/ doing the same publishing steps.  test pypi and regular pypi are completely independent.  

You'll need to replace THENAME in [README.rst](https://github.com/utelle/apsw-sqlite3mc/blob/sqlite3mc/README.rst) with whatever the name at the pypis is.

**Comment by utelle** [comment]
> You should create another account at regular https://pypi.org/ doing the same publishing steps. test pypi and regular pypi are completely independent.

I already created a regular pypi account shortly after I created the test pypi account, after detecting that they are independent of each other.

> You'll need to replace THENAME in [README.rst](https://github.com/utelle/apsw-sqlite3mc/blob/sqlite3mc/README.rst) with whatever the name at the pypis is.

I intend to use **sqlite3mc** as the name, so that the final package name will be **apsw-sqlite3mc**.

**Comment by utelle** [comment]
In the readme file I replaced the placeholder _THENAME_ by _sqlite3mc_.

One question:

At the moment only the _SQLite3 Multiple Ciphers_ logo is shown at the beginning of the readme file. IMHO it would make sense to display also the APSW logo, because this project is a combination of both projects. Is this possible with _reStructured Text_? If yes, how?

**Comment by rogerbinns** [comment]
I'm fine not having the APSW logo there.  Restructured text can have both logos there, but the github renderer doesn''t do things correctly.  For example the logo is set to show on the right side which they don't do.

**Comment by utelle** [comment]
> I'm fine not having the APSW logo there.

I'm not. This new project is a combination of APSW and SQLite3MC. So, it shouldn't use neither of the logos alone, but also a combination of the logos.

> Restructured text can have both logos there, but the github renderer doesn''t do things correctly. For example the logo is set to show on the right side which they don't do.

IMHO placing the logos side by side would be good enough. And I modified the readme accordingly. But maybe I create a new graphics for the combined logos.

**Comment by rogerbinns** [comment]
You really don't need the APSW logo or two logos.  SQLite is what does the heavy lifting behind both our projects!

The readme text makes it clear that the project is a combination of apsw, sqlite, and multiple ciphers.  That is sufficient and clear.

Any developer using this has to type `import apsw` as their first line of code, and has to refer to the apsw doc because even opening a database is different than the builtin sqlite3 module.

The reason APSW even has a logo is because that README becomes part of the long description of the package and what is shown on the [pypi page](https://pypi.org/project/apsw/).  Virtually every pypi page is bland blob of text - [one random example](https://pypi.org/project/uniseg/) - so it was a way being aesthetically different - ie purely cosmetic reasons.

Heck the logo itself is not some master branding exercise  - it is just a snake for Python, a feather for SQLite, and a ring because I am a fan of [stargate](https://en.wikipedia.org/wiki/Stargate_SG-1).

Having just the sqlitre3mc logo on the pypi page would be enough to confirm to someone that they have found the right place.

I didn't need the logo to show up on the github page, but am not going to spend the effort to have different readme for github versus pypi.

So really, I encourage you to keep it simple and have it as it was with just the sqlite3mc logo!

**Comment by rogerbinns** [comment]
Amusingly the '+' is almost invisible on github.  In any event it will only be once published to test pypi that you'll see what it will really look like.

**Comment by utelle** [comment]
> Amusingly the '+' is almost invisible on github.

Yes ... and that is certainly not what I'd like to have. Therefore I will probably create a single graphic expressing what I want.

> You really don't need the APSW logo or two logos. SQLite is what does the heavy lifting behind both our projects!

Of course, SQLite is behind both projects, but for the Python user the interface of both projects looks like APSW.

Additionally, in case I decide to create a `pysqlite3` based variant with encryption support someday in the future, it would confuse the Python users, if the same _SQLite3MC_ logo would be used for both packages.

Creating a logo is certainly not the most urgent task, but I still think it should be done and should be some sort of combination of the APSW and SQLite3MC logo.

**Comment by rogerbinns** [comment]
This is now working.  The results can be seen at https://test.pypi.org/project/apsw-sqlite3mc/

In [this commit](https://github.com/utelle/apsw-sqlite3mc/commit/2262d499a406440c89839c71fe8bdd22ba056ab8) I added the new logo from Ulrich.

In [this commit](https://github.com/utelle/apsw-sqlite3mc/commit/bb3369ca7aee7f3b653677b2643d658c4a4f8270) I fixed up some README text, and added multiple documentation links to show up in pypi to ensure there are links to all the doc.

Closing.

**Comment by rogerbinns** [comment]
PyPI download was tested by installing it and running the test suite.  Installed directory contents were visually inspected.

Having pip do a source download and then build failed.

    pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/  --no-binary ":all:" apsw-sqlite3mc

This is because the configure directory was not included.
