### ISSUE TITLE
PyPI package not available

### ISSUE THREAD

**Issue by richboss** [utelle/apsw-sqlite3mc#9]
The installation with `pip install apsw-sqlite3mc` does not work as no matching distribution is found. Additionally the PyPI website does not know anything about `apsw-sqlite3mc`.

**Comment by rogerbinns** [comment]
Thanks for your interest in APSW and SQLite3 Multiple Ciphers.

You have caught us in the final stages of putting together the first release.  That release will happen in the next few days.    You can try our final test release from [test.pypi.org](https://test.pypi.org/project/apsw-sqlite3mc/) immediately, or wait a few days.

Any feedback you have is appreciated.

**Comment by utelle** [comment]
The first official [apsw-sqlite3mc](https://pypi.org/project/apsw-sqlite3mc/) release is now [available](https://pypi.org/project/apsw-sqlite3mc/). Please give it a try.

Feedback is welcome.

**Comment by richboss** [comment]
Thank you! Installation via pip was smooth and quick. For testing purposes I "converted" a Peewee application from sqlite_ext to apsw_ext by changing only two lines of code. It worked out of the box. Very nice!
